name: Zara Fiyat Takip

on:
  schedule:
    - cron: '*/5 * * * *'  # Her 5 dakikada bir
  workflow_dispatch:  # Manuel çalıştırma

jobs:
  check-price:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install requests
      
      - name: Get last price
        id: get-price
        run: |
          if [ -f price.txt ]; then
            echo "LAST_PRICE=$(cat price.txt)" >> $GITHUB_ENV
          fi
      
      - name: Run tracker
        id: tracker
        env:
          LAST_PRICE: ${{ env.LAST_PRICE }}
        run: python zara_tracker.py
      
      - name: Save new price
        run: |
          if [ -n "${{ steps.tracker.outputs.price }}" ]; then
            echo "${{ steps.tracker.outputs.price }}" > price.txt
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add price.txt
            git diff --staged --quiet || git commit -m "Update price"
            git push
          fi
